[package]
name = "bizkitdatabase"
edition = "2021"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
bizkitdata = { path = "../data"}
postgres.workspace = true
base64.workspace = true