[package]
name = "bizkitdb"
edition = "2021"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
bizkitdata = { path = "../data/"}
serde.workspace = true
rusqlite.workspace = true